### ISSUE TITLE
DataStore modelgen fails on union type

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-swift#544]
**Describe the bug**
When I create union type for search and try to generate DataStore models I've got error
```
Unknown type SearchResult for field items. Did you forget to add the @model directive
```

**To Reproduce**
Create schema with union and use union in any type
```
union SearchResult = Contact | User | Entity
type SearchableConnection {
  items: [SearchResult]
  nextToken: String
  total: Int
}
```

**Expected behavior**
Successfully generate models

**Comment by drochetti** [comment]
@lenarmazitov as of now union types are not supported in DataStore. However that error message is not clear about it.

I filed an issue in the CLI repo: https://github.com/aws-amplify/amplify-cli/issues/4566 and marked this one as a feature request.

**Comment by iShavgula-TacTill** [comment]
Hello,
Do you plan to support union types in DataStore and if you do - do you have an ETA for it ?

**Comment by ohdonpiano** [comment]
+1 
same here, follows an extract of schema:

`
union GenericData = AdditionalService | Installment | Loan

type GenericResults {
  count: Int
  data: [GenericData]
  error: Error
}

type Query {
  additional_services(filterOptions: FilterOptions_v2, orderOptions: OrderOptions, pageOptions: PageOptions): GenericResults
}
`

executing _amplify codegen models_ the following error is returned:

`
GraphQL schema compiled successfully.

Edit your schema at /Users/dpoggi/code/Redo/redo-ios-app/amplify/backend/api/amplifyDatasource/schema.graphql or place .graphql files in a directory at /Users/dpoggi/code/Redo/redo-ios-app/amplify/backend/api/amplifyDatasource/schema
App not deployed yet.
Unknown type GenericData for field data. Did you forget to add the @model directive
Error: Unknown type GenericData for field data. Did you forget to add the @model directive
    at AppSyncSwiftVisitor.getNativeType (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/appsync-modelgen-plugin/src/visitors/appsync-visitor.ts:393:13)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts:215:32
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts:214:33
    at Array.forEach (<anonymous>)
    at AppSyncSwiftVisitor.generateNonModelType (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts:209:49)
    at AppSyncSwiftVisitor.generate (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/appsync-modelgen-plugin/src/visitors/appsync-swift-visitor.ts:69:22)
    at Object.exports.plugin (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@aws-amplify/appsync-modelgen-plugin/src/plugin.ts:54:20)
    at Object.executePlugin (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-codegen/core/src/execute-plugin.ts:54:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-codegen/core/src/codegen.ts:74:28
    at Array.map (<anonymous>)
    at Object.codegen (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-codegen/core/src/codegen.ts:61:21)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:126:23
    at Array.map (<anonymous>)
    at Object.generateModels (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:125:46)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/commands/codegen/models.js:9:7)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/amplify-plugin-index.js:9:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
`

**Comment by ucheNkadiCode** [comment]
This addition would seriously simplify my use case. It's difficult to store self referential arrays without this feature

```graphql
#... defining Workout and WorkoutFolder as separate types above
union WorkoutOrWorkoutFolder = Workout | WorkoutFolder

type HybridWorkoutFolder @model @auth(rules: [{ allow: owner }]) {
  fullList: [WorkoutOrWorkoutFolder!]!
}
```

**Comment by atierian** [comment]
Closing as this is related to codegen and not Amplify Swift specific.
Please follow https://github.com/aws-amplify/amplify-codegen/issues/211 for updates.
